@startuml StateDiagramm
state "Init" as systemInit{
    state "get MAC" as sysinit_getmac
    state "calc default IP" as sysinit_calcdefip
    state "set callback functions" as sysinit_setcbfunc
    state "set system mode" as sysinit_setsysmode
    sysinit_setsysmode : NODE 
    sysinit_setsysmode : CONTROLLER

    [*] -d-> sysinit_getmac
    sysinit_getmac -d-> sysinit_calcdefip
    sysinit_calcdefip -d-> sysinit_setsysmode
    sysinit_setsysmode -d-> sysinit_setcbfunc
    sysinit_setcbfunc -d-> [*]
}
state "Idle" as systemIdle{

}
systemIdle : waiting for packets
state "packet processing" as packetProc{

}
state "configuring" as systemConf{

}
state "error" as syserror{
    state "log error" as syserror_log
    state "attempt fix" as syserror_fix

    [*] -d-> syserror_log
    syserror_log -d-> syserror_fix
    syserror_fix -d-> [*] : fixed or max retry
    syserror_fix -> syserror_fix : retry

    
}

[*]  -> systemInit
systemInit -> systemConf
systemConf -> systemIdle
systemIdle -> packetProc


systemInit -d-> syserror
systemConf -d-> syserror
systemIdle -d-> syserror
packetProc -d-> syserror
syserror -d-> [*] : if error ist not correctable terminate



@enduml